# Generated by Django 2.2.6 on 2019-12-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191130_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.AddField(
            model_name='activity',
            name='assigned_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='files',
            field=models.ManyToManyField(blank=True, to='app.Attachment'),
        ),
        migrations.CreateModel(
            name='ActivityDelistRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delist_requests', to='app.Activity')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvers', to='app.Member')),
            ],
            options={
                'verbose_name': 'Avbokningsbegäran',
                'verbose_name_plural': 'Avbokningsbegäranden',
                'ordering': ['activity__assigned', 'activity__date'],
            },
        ),
    ]
