# Generated by Django 2.2.8 on 2019-12-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191207_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydelistrequest',
            options={'ordering': ['activity__assigned', 'activity__date'], 'verbose_name': 'Avbokningsförfrågan', 'verbose_name_plural': 'Avbokningsförfråganden'},
        ),
        migrations.AddField(
            model_name='activitydelistrequest',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='delist_request_members', to='app.Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitydelistrequest',
            name='reject_readon',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activitydelistrequest',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
