# Generated by Django 2.2.8 on 2019-12-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191208_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitydelistrequest',
            old_name='reject_readon',
            new_name='reject_reason',
        ),
        migrations.AlterField(
            model_name='activity',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
