# Generated by Django 2.2.8 on 2019-12-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191214_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydelistrequest',
            options={'ordering': ['activity__assigned', 'activity__date'], 'verbose_name': 'Avbokningsbegäran', 'verbose_name_plural': 'Avbokningsbegäranden'},
        ),
        migrations.RenameField(
            model_name='activitytype',
            old_name='files',
            new_name='attachments',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='files',
            new_name='attachments',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='files',
            new_name='attachments',
        ),
    ]
