# Generated by Django 2.2.6 on 2019-12-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_member_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='licensed_driver',
        ),
    ]
