# Generated by Django 2.2.8 on 2020-01-01 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_member_licensed_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydelistrequest',
            options={'ordering': ['activity__date', 'activity__assigned'], 'verbose_name': 'Avbokningsbegäran', 'verbose_name_plural': 'Avbokningsbegäranden'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='completed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='activitydelistrequest',
            unique_together={('member', 'activity')},
        ),
    ]
