# Generated by Django 2.2.8 on 2020-01-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200101_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fullname',
        ),
        migrations.AddField(
            model_name='member',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
