# Generated by Django 2.2.8 on 2020-01-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydelistrequest',
            options={'ordering': ['activity__date', 'activity__assigned'], 'verbose_name': 'Avbokning', 'verbose_name_plural': 'Avbokningar'},
        ),
        migrations.AddField(
            model_name='member',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='email_verification_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
