# Generated by Django 2.2.8 on 2020-01-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200103_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='coordinators',
        ),
        migrations.AddField(
            model_name='event',
            name='coordinators',
            field=models.ManyToManyField(blank=True, to='app.Member'),
        ),
    ]
