# Generated by Django 2.2.6 on 2020-01-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200105_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Informationstext',
                'verbose_name_plural': 'Informationstexter',
            },
        ),
    ]
