# Generated by Django 2.2.6 on 2020-01-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200107_1738'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitydelistrequest',
            index=models.Index(fields=['member'], name='app_activit_member__1b8029_idx'),
        ),
        migrations.AddIndex(
            model_name='activitydelistrequest',
            index=models.Index(fields=['activity'], name='app_activit_activit_32cf33_idx'),
        ),
        migrations.AddIndex(
            model_name='activitydelistrequest',
            index=models.Index(fields=['member', 'activity'], name='app_activit_member__4fe69e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitydelistrequest',
            index=models.Index(fields=['approver'], name='app_activit_approve_ec2cd5_idx'),
        ),
    ]
