# Generated by Django 2.2.6 on 2020-01-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200107_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', 'question'], 'verbose_name': 'Vanlig fråga', 'verbose_name_plural': 'Vanliga frågor'},
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
