# Generated by Django 2.2.6 on 2020-01-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200107_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
