# Generated by Django 2.2.6 on 2020-01-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200107_1815'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['assigned'], name='app_activit_assigne_aac0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['event'], name='app_activit_event_i_6c0bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['event', 'assigned'], name='app_activit_event_i_899896_idx'),
        ),
    ]
