# Generated by Django 2.2.6 on 2020-01-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200107_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='app.Attachment'),
        ),
    ]
