# Generated by Django 2.2.6 on 2020-01-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_activity_attachments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Bifogad fil', 'verbose_name_plural': 'Bifogade filer'},
        ),
        migrations.AddField(
            model_name='activity',
            name='earliest_bookable_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
