# Generated by Django 2.2.8 on 2020-01-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200112_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='fee_reimbursed',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='food_included',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='rental_kart',
        ),
        migrations.AddField(
            model_name='activitytype',
            name='fee_reimbursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='food_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='rental_kart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Påminnelse bekräftad'),
        ),
    ]
