# Generated by Django 2.2.9 on 2020-01-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20200113_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={'ordering': ['name'], 'verbose_name': 'Uppgiftstyp', 'verbose_name_plural': 'Uppgiftstyper'},
        ),
    ]
