# Generated by Django 2.2.9 on 2020-01-18 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200118_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='proxy_for',
        ),
        migrations.AddField(
            model_name='activity',
            name='assigned_for_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_via_proxies', to='app.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='proxy',
            field=models.ManyToManyField(blank=True, related_name='_member_proxy_+', to='app.Member', verbose_name='Huvudman'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
