# Generated by Django 2.2.6 on 2020-01-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200118_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='min_signup_bias',
            field=models.IntegerField(default=0, verbose_name='Justeringsfaktor för åtaganaden'),
        ),
    ]
