# Generated by Django 2.2.6 on 2020-01-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_member_min_signup_bias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
