# Generated by Django 2.2.9 on 2020-01-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20200123_0733'),
        ('app', '0036_auto_20200120_2018'),
    ]

    operations = [
    ]
