# Generated by Django 2.2.9 on 2020-02-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200118_1618'),
        ('app', '0037_merge_20200123_0637'),
    ]

    operations = [
    ]
