# Generated by Django 2.2.10 on 2020-03-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20200315_1610'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'end_date'], name='app_event_start_d_3ad137_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type'], name='app_event_type_id_31fcb5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['cancelled'], name='app_event_cancell_b7c744_idx'),
        ),
    ]
