# Generated by Django 2.2.11 on 2020-05-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200315_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='assigned_for_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_via_proxies', to='app.Member', verbose_name='Tilldelad som underhuggare åt'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Bekräftad'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Värde'),
        ),
    ]
