# Generated by Django 2.2.10 on 2020-06-12 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200315_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('abbrev', models.CharField(max_length=6, unique=True)),
                ('comment', models.TextField()),
                ('min_age', models.PositiveSmallIntegerField(verbose_name='Minsta ålder')),
                ('max_age', models.PositiveSmallIntegerField(verbose_name='Högsta ålder')),
                ('min_weight', models.PositiveSmallIntegerField(verbose_name='Minsta vikt')),
            ],
            options={
                'verbose_name': 'Klass',
                'verbose_name_plural': 'Klasser',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Namn')),
                ('description', models.TextField(verbose_name='Beskrivning')),
                ('start_level', models.CharField(max_length=1, verbose_name='Första nivån')),
                ('end_level', models.CharField(max_length=1, verbose_name='Sista nivån')),
            ],
            options={
                'verbose_name': 'Licenstyp',
                'verbose_name_plural': 'Licenstyper',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='assigned_for_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_via_proxies', to='app.Member', verbose_name='Tilldelad som underhuggare åt'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Bekräftad'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Värde'),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=1, verbose_name='Nivå')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Member', verbose_name='Innehavare')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LicenseType', verbose_name='Licenstyp')),
            ],
            options={
                'verbose_name': 'Licens',
                'verbose_name_plural': 'Licenser',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='licenses',
            field=models.ManyToManyField(through='app.License', to='app.LicenseType', verbose_name='Licenser'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Namn')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Nummer')),
                ('birthday', models.DateField(verbose_name='Födelsedatum')),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.CarClass')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Member')),
            ],
            options={
                'verbose_name': 'Förare',
                'verbose_name_plural': 'Förare',
                'ordering': ['member', 'name'],
                'unique_together': {('member', 'name', 'number')},
            },
        ),
    ]
