# Generated by Django 2.2.10 on 2020-06-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20200612_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarClassification',
            new_name='CarClass',
        ),
    ]
