# Generated by Django 2.2.10 on 2020-06-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20200612_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['member', 'name'], 'verbose_name': 'Förare/Fordon', 'verbose_name_plural': 'Förare/Fordon'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='licenses',
        ),
        migrations.AlterField(
            model_name='carclass',
            name='max_age',
            field=models.PositiveSmallIntegerField(default=99, verbose_name='Högsta ålder'),
        ),
        migrations.AlterField(
            model_name='carclass',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Minsta ålder'),
        ),
        migrations.AlterField(
            model_name='carclass',
            name='min_weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Minsta vikt'),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Namn'),
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('type', 'member')},
        ),
    ]
