# Generated by Django 2.2.10 on 2020-06-12 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20200612_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=1, verbose_name='Nivå')),
            ],
            options={
                'verbose_name': 'Licens',
                'verbose_name_plural': 'Licenser',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='licenses',
            field=models.ManyToManyField(through='app.License', to='app.LicenseType', verbose_name='Licenser'),
        ),
        migrations.AddField(
            model_name='license',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Member', verbose_name='Innehavare'),
        ),
        migrations.AddField(
            model_name='license',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LicenseType', verbose_name='Licenstyp'),
        ),
    ]
