# Generated by Django 2.2.10 on 2020-07-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20200612_2233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='license',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(fields=('type', 'member'), name='license_type_per_member'),
        ),
    ]
