# Generated by Django 2.2.11 on 2020-07-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20200724_1527'),
        ('app', '0042_auto_20200510_1518'),
    ]

    operations = [
    ]
