# Generated by Django 2.2.6 on 2019-11-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191102_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
